services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ollama 
    environment:
      - MONGO_URI=mongodb://mongo:27017/my-banker
      - OLLAMA_API=http://ollama:11434
    volumes:
      - ./backend:/usr/src/app/backend
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  ollama:
      image: ollama/ollama
      container_name: ollama
      ports:
        - "11434:11434"
      volumes:
        - ollama-data:/root/.ollama
      restart: unless-stopped
      privileged: true

volumes:
  mongo-data:
  ollama-data:
