services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - ollama
    environment:
      - MONGO_URI=${MONGO_URI}
      - OLLAMA_API=${OLLAMA_API}
      - JWT_SECRET=${JWT_SECRET}
      - MORALIS_API_KEY=${MORALIS_API_KEY}
    volumes:
      - ./backend:/usr/src/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    privileged: true

volumes:
  mongo-data:
  ollama-data: